name: .NET CI/CD

on:
  push:
    branches: [ "development", "main", "feature/*" ]
  pull_request:
    branches: [ "development", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build  # This ensures Test only runs if Build passes
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Test
      run: dotnet test --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: test  # Only deploy if tests pass!
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    
    steps:
    - uses: actions/checkout@v4

    - name: Generate Deployment Package
      run: zip -r deploy.zip . -x "*.git*"

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: 'EncryptionApiCICD'
        environment_name: 'EncryptionApi-env-1'
        region: 'us-east-1' 
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip
    